### ISSUE TITLE
Use kubernetes-client BOM for dependencies

### ISSUE THREAD

**Issue by andreaTP** [skodjob/odh-e2e#139]
I think it's a good idea to rely on the `kubernetes-client-bom` to avoid issues on the classpath and random failures at runtime.

We are already using it here: https://github.com/skodjob/opendatahub-crds/blob/3d1e4724402f81e288dd3503aeb0a56ecc1260f0/pom.xml#L67

**Comment by kornys** [comment]
makes sense, going to open PR :) thanks
