### ISSUE TITLE
Somehow log the place where utils methods were called, not the lines inside the utils methods

### ISSUE THREAD

**Issue by jiridanek** [skodjob/odh-e2e#154]
This log message is not helpful for quickly jumping to the relevant place in the test

```
2024-07-14 02:30:03 [main] INFO  [Wait:65] Waiting for: pipelineRun to complete
```

I'd like to log not the line in the helper method for waiting, but the location where the wait method was called.

Possibly both can be logged at the same time, in case the wait method itself needed investigating.

**Comment by kornys** [comment]
it requires update in test-frame

**Comment by jiridanek** [comment]
Discussed in person, there is no good way to find out how much up in the stacktrace we should look. We could look for a class that ends with "ST", or something like that. Or print last 5 stack frames and hope it will get into familiar territory. But nothing sounds especially lovable.
